// PDF Generator for Vercel Serverless - Chrome-free approach
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');

console.log('PDF Generator loaded. Environment:', {
  VERCEL: process.env.VERCEL,
  NODE_ENV: process.env.NODE_ENV,
  isVercel: process.env.VERCEL === '1'
});

// Simple HTML to text converter (basic implementation)
function htmlToText(html) {
  return html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Extract basic data from HTML
function extractInvoiceData(html) {
  const text = htmlToText(html);
  
  // Simple extraction - in a real implementation, you'd parse the HTML properly
  const lines = text.split(' ').filter(word => word.length > 0);
  
  return {
    title: 'Invoice',
    content: text.substring(0, 1000), // Limit content length
    lines: lines.slice(0, 50) // Limit number of lines
  };
}

async function generatePDF(html, options = {}) {
  try {
    console.log('Starting PDF generation with pdf-lib...');
    
    // Create a new PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4 size
    
    // Get the standard font
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    
    // Extract data from HTML
    const data = extractInvoiceData(html);
    
    // Set up page dimensions
    const { width, height } = page.getSize();
    const margin = 50;
    const contentWidth = width - 2 * margin;
    let yPosition = height - margin;
    
    // Add title
    page.drawText(data.title, {
      x: margin,
      y: yPosition,
      size: 24,
      font: boldFont,
      color: rgb(0, 0, 0)
    });
    
    yPosition -= 40;
    
    // Add timestamp
    const timestamp = new Date().toLocaleString();
    page.drawText(`Generated: ${timestamp}`, {
      x: margin,
      y: yPosition,
      size: 10,
      font: font,
      color: rgb(0.5, 0.5, 0.5)
    });
    
    yPosition -= 30;
    
    // Add environment info
    const envInfo = `Environment: ${process.env.VERCEL === '1' ? 'Vercel Serverless' : 'Local Development'}`;
    page.drawText(envInfo, {
      x: margin,
      y: yPosition,
      size: 10,
      font: font,
      color: rgb(0.5, 0.5, 0.5)
    });
    
    yPosition -= 30;
    
    // Add content (simplified)
    const maxLines = 20;
    const lineHeight = 14;
    const wordsPerLine = 15;
    
    let currentLine = '';
    let lineCount = 0;
    
    for (const word of data.lines) {
      if (lineCount >= maxLines) break;
      
      if (currentLine.split(' ').length >= wordsPerLine) {
        // Draw current line
        page.drawText(currentLine, {
          x: margin,
          y: yPosition,
          size: 12,
          font: font,
          color: rgb(0, 0, 0)
        });
        
        yPosition -= lineHeight;
        lineCount++;
        currentLine = word;
      } else {
        currentLine += (currentLine ? ' ' : '') + word;
      }
    }
    
    // Draw remaining text
    if (currentLine && lineCount < maxLines) {
      page.drawText(currentLine, {
        x: margin,
        y: yPosition,
        size: 12,
        font: font,
        color: rgb(0, 0, 0)
      });
    }
    
    // Add watermark if enabled
    if (process.env.ENABLE_WATERMARK === 'true' || options.watermark) {
      const watermarkText = process.env.WATERMARK_TEXT || 'SAMPLE INVOICE';
      
      // Add watermark in center
      page.drawText(watermarkText, {
        x: width / 2 - 100,
        y: height / 2,
        size: 48,
        font: boldFont,
        color: rgb(0.8, 0.8, 0.8),
        opacity: 0.3
      });
    }
    
    // Add footer
    page.drawText('Generated by Invoice Generator API', {
      x: margin,
      y: margin,
      size: 10,
      font: font,
      color: rgb(0.5, 0.5, 0.5)
    });
    
    // Serialize the PDF
    const pdfBytes = await pdfDoc.save();
    console.log('PDF generated successfully with pdf-lib, size:', pdfBytes.length, 'bytes');
    
    return Buffer.from(pdfBytes);
    
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
}

// Generate PDF with retry mechanism
const generatePDFWithRetry = async (html, options = {}, maxRetries = 2) => {
  let lastError;
  
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`PDF generation attempt ${attempt}/${maxRetries}`);
      return await generatePDF(html, options);
    } catch (error) {
      lastError = error;
      console.warn(`PDF generation attempt ${attempt} failed:`, error.message);
      
      if (attempt < maxRetries) {
        const waitTime = Math.min(Math.pow(2, attempt) * 1000, 3000);
        console.log(`Waiting ${waitTime}ms before retry...`);
        await new Promise(resolve => setTimeout(resolve, waitTime));
      }
    }
  }
  
  throw lastError;
};

// Health check function
const healthCheck = async () => {
  try {
    console.log('Running health check...');
    const testHtml = '<html><body><h1>Test Invoice</h1><p>This is a test invoice.</p></body></html>';
    await generatePDF(testHtml, { format: 'A4' });
    return { 
      status: 'healthy', 
      message: 'PDF generation is working correctly',
      environment: 'Vercel Serverless',
      method: 'pdf-lib (Chrome-free)'
    };
  } catch (error) {
    return { 
      status: 'unhealthy', 
      message: error.message,
      environment: 'Vercel Serverless',
      method: 'pdf-lib (Chrome-free)'
    };
  }
};

module.exports = {
  generatePDF: generatePDFWithRetry,
  healthCheck
}; 