const fs = require('fs').promises;
const path = require('path');
const Handlebars = require('handlebars');

// Cache for compiled templates and translations (optimized for serverless)
const templateCache = new Map();
const translationCache = new Map();

// Load and cache translation file with serverless-optimized error handling
const loadTranslations = async (locale) => {
  if (translationCache.has(locale)) {
    return translationCache.get(locale);
  }

  try {
    const translationPath = path.join(__dirname, '../locales', `${locale}.json`);
    
    // Check if file exists first
    try {
      await fs.access(translationPath);
    } catch (accessError) {
      console.warn(`Translation file not found for locale: ${locale}, falling back to English`);
      if (locale !== 'en') {
        return await loadTranslations('en');
      }
      throw new Error('English translation file not found');
    }

    const translationData = await fs.readFile(translationPath, 'utf8');
    const translations = JSON.parse(translationData);
    
    // Validate translation object
    if (!translations || typeof translations !== 'object') {
      throw new Error(`Invalid translation format for locale: ${locale}`);
    }
    
    translationCache.set(locale, translations);
    return translations;
  } catch (error) {
    // If English also fails, return comprehensive default translations
    if (locale === 'en' || error.message.includes('English translation')) {
      const defaultTranslations = {
        invoice: 'Invoice',
        invoiceNumber: 'Invoice Number',
        date: 'Date',
        dueDate: 'Due Date',
        billTo: 'Bill To',
        billFrom: 'Bill From',
        description: 'Description',
        quantity: 'Qty',
        unitPrice: 'Unit Price',
        price: 'Price',
        amount: 'Amount',
        subtotal: 'Subtotal',
        tax: 'Tax',
        shipping: 'Shipping',
        serviceFee: 'Service Fee',
        total: 'Total',
        notes: 'Notes',
        paymentTerms: 'Payment Terms',
        bankAccount: 'Bank Account',
        phone: 'Phone',
        email: 'Email',
        taxNumber: 'Tax Number',
        vatNumber: 'VAT Number',
        thankYou: 'Thank you for your business!',
        generatedOn: 'Generated on',
        poweredBy: 'Generated by Invoice API'
      };
      
      translationCache.set('en', defaultTranslations);
      return defaultTranslations;
    }
    
    // Fallback to English for other locales
    if (locale !== 'en') {
      return await loadTranslations('en');
    }
    
    throw error;
  }
};

// Load and cache template with serverless-optimized error handling
const loadTemplate = async (templateNumber) => {
  const cacheKey = `template_${templateNumber}`;
  
  if (templateCache.has(cacheKey)) {
    return templateCache.get(cacheKey);
  }

  try {
    const templatePath = path.join(__dirname, '../templates', `template${templateNumber}.html`);
    
    // Check if template file exists
    try {
      await fs.access(templatePath);
    } catch (accessError) {
      console.warn(`Template ${templateNumber} not found, falling back to template 1`);
      if (templateNumber !== 1) {
        return await loadTemplate(1);
      }
      throw new Error('Default template not found');
    }

    const templateContent = await fs.readFile(templatePath, 'utf8');
    
    // Validate template content
    if (!templateContent || templateContent.trim().length === 0) {
      throw new Error(`Template ${templateNumber} is empty`);
    }

    const compiledTemplate = Handlebars.compile(templateContent);
    
    templateCache.set(cacheKey, compiledTemplate);
    return compiledTemplate;
  } catch (error) {
    if (templateNumber !== 1) {
      console.warn(`Error loading template ${templateNumber}:`, error.message);
      return await loadTemplate(1);
    }
    
    throw new Error(`Failed to load default template: ${error.message}`);
  }
};

// Register comprehensive Handlebars helpers
const registerHelpers = () => {
  // Format currency helper with better error handling
  Handlebars.registerHelper('formatCurrency', function(amount, currency) {
    try {
      const num = parseFloat(amount) || 0;
      const currencySymbols = {
        'USD': '$',
        'EUR': '€',
        'GBP': '£',
        'CAD': 'C$',
        'AUD': 'A$',
        'JPY': '¥',
        'CHF': 'CHF',
        'SEK': 'kr',
        'NOK': 'kr',
        'DKK': 'kr',
        'INR': '₹',
        'CNY': '¥',
        'BRL': 'R$',
        'ZAR': 'R'
      };
      
      const symbol = currencySymbols[currency] || (currency || '$');
      
      // Handle different currency formatting
      if (currency === 'JPY') {
        return `${symbol}${Math.round(num)}`;
      }
      
      return `${symbol}${num.toFixed(2)}`;
    } catch (error) {
      console.warn('Currency formatting error:', error);
      return amount || '0.00';
    }
  });

  // Format date helper with better error handling
  Handlebars.registerHelper('formatDate', function(dateString, locale) {
    if (!dateString) return '';
    
    try {
      const date = new Date(dateString);
      
      // Check if date is valid
      if (isNaN(date.getTime())) {
        console.warn('Invalid date:', dateString);
        return dateString;
      }
      
      const options = { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      };
      
      return date.toLocaleDateString(locale || 'en-US', options);
    } catch (error) {
      console.warn('Date formatting error:', error);
      return dateString || '';
    }
  });

  // Calculate line total helper
  Handlebars.registerHelper('calculateTotal', function(quantity, price) {
    try {
      const qty = parseFloat(quantity) || 0;
      const prc = parseFloat(price) || 0;
      return (qty * prc).toFixed(2);
    } catch (error) {
      console.warn('Calculate total error:', error);
      return '0.00';
    }
  });

  // Format number helper
  Handlebars.registerHelper('formatNumber', function(number, decimals = 2) {
    try {
      const num = parseFloat(number) || 0;
      return num.toFixed(decimals);
    } catch (error) {
      console.warn('Number formatting error:', error);
      return '0.00';
    }
  });

  // Conditional helper for optional fields
  Handlebars.registerHelper('ifExists', function(value, options) {
    if (value && value !== '' && value !== null && value !== undefined) {
      return options.fn(this);
    }
    return options.inverse(this);
  });

  // Safe string helper
  Handlebars.registerHelper('safeString', function(str) {
    if (!str) return '';
    return new Handlebars.SafeString(str);
  });

  // Array length helper
  Handlebars.registerHelper('arrayLength', function(array) {
    return Array.isArray(array) ? array.length : 0;
  });

  // Math helpers
  Handlebars.registerHelper('add', function(a, b) {
    return (parseFloat(a) || 0) + (parseFloat(b) || 0);
  });

  Handlebars.registerHelper('multiply', function(a, b) {
    return (parseFloat(a) || 0) * (parseFloat(b) || 0);
  });

  // Comparison helpers
  Handlebars.registerHelper('eq', function(a, b) {
    return a === b;
  });

  Handlebars.registerHelper('gt', function(a, b) {
    return (parseFloat(a) || 0) > (parseFloat(b) || 0);
  });

  Handlebars.registerHelper('lt', function(a, b) {
    return (parseFloat(a) || 0) < (parseFloat(b) || 0);
  });
};

// Initialize helpers
registerHelpers();

// Validate invoice data structure
const validateInvoiceData = (invoiceData) => {
  const requiredFields = ['invoiceNumber', 'companyName', 'productOrService', 'taxPercent', 'currency', 'date'];
  const missingFields = requiredFields.filter(field => !invoiceData[field]);
  
  if (missingFields.length > 0) {
    throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
  }
  
  if (!Array.isArray(invoiceData.productOrService) || invoiceData.productOrService.length === 0) {
    throw new Error('At least one product or service is required');
  }
  
  return true;
};

// Calculate totals with error handling
const calculateTotals = (invoiceData) => {
  try {
    const subtotal = invoiceData.productOrService.reduce((sum, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return sum + (quantity * price);
    }, 0);

    const taxPercent = parseFloat(invoiceData.taxPercent) || 0;
    const taxAmount = (subtotal * taxPercent) / 100;
    const shippingAmount = parseFloat(invoiceData.shippingAmount) || 0;
    const serviceFee = parseFloat(invoiceData.serviceFee) || 0;
    const total = subtotal + taxAmount + shippingAmount + serviceFee;

    return {
      subtotal: subtotal.toFixed(2),
      taxAmount: taxAmount.toFixed(2),
      shippingAmount: shippingAmount.toFixed(2),
      serviceFee: serviceFee.toFixed(2),
      total: total.toFixed(2)
    };
  } catch (error) {
    console.error('Error calculating totals:', error);
    throw new Error('Failed to calculate invoice totals');
  }
};

// Main template rendering function optimized for serverless
const renderTemplate = async (invoiceData) => {
  try {
    // Validate input data
    validateInvoiceData(invoiceData);
    
    // Set defaults
    const templateNumber = invoiceData.template || 1;
    const locale = invoiceData.locale || 'en';
    
    // Load translations and template in parallel
    const [translations, template] = await Promise.all([
      loadTranslations(locale),
      loadTemplate(templateNumber)
    ]);
    
    // Calculate totals
    const totals = calculateTotals(invoiceData);
    
    // Prepare data for template
    const templateData = {
      ...invoiceData,
      ...totals,
      translations,
      locale,
      generatedAt: new Date().toISOString(),
      // Add computed fields
      hasBuyerCompany: !!(invoiceData.buyerCompany && invoiceData.buyerCompany.name),
      hasSellerCompany: !!(invoiceData.sellerCompany && invoiceData.sellerCompany.name),
      hasBuyer: !!(invoiceData.buyerCompany && invoiceData.buyerCompany.name),
      hasSeller: !!(invoiceData.sellerCompany && invoiceData.sellerCompany.name),
      hasShipping: parseFloat(invoiceData.shippingAmount) > 0,
      hasServiceFee: parseFloat(invoiceData.serviceFee) > 0,
      hasNotes: !!(invoiceData.notes && invoiceData.notes.trim()),
      hasPaymentTerms: !!(invoiceData.paymentTerms && invoiceData.paymentTerms.trim()),
      hasDueDate: !!(invoiceData.dueDate),
      hasLogo: !!(invoiceData.companyLogo),
      // Format dates
      formattedDate: invoiceData.date ? new Date(invoiceData.date).toLocaleDateString(locale) : '',
      formattedDueDate: invoiceData.dueDate ? new Date(invoiceData.dueDate).toLocaleDateString(locale) : '',
      // Add items array with correct field names for templates
      items: invoiceData.productOrService.map(item => ({
        name: item.description || item.name || 'Item',
        description: item.description || '',
        quantity: item.quantity || 0,
        price: item.price || 0,
        lineTotal: (parseFloat(item.quantity) * parseFloat(item.price)).toFixed(2)
      })),
      // Keep the original for backward compatibility
      itemsWithTotals: invoiceData.productOrService.map(item => ({
        ...item,
        total: (parseFloat(item.quantity) * parseFloat(item.price)).toFixed(2)
      }))
    };
    
    // Render template
    const html = template(templateData);
    
    return html;
    
  } catch (error) {
    console.error('Template rendering error:', error);
    throw new Error(`Failed to render invoice template: ${error.message}`);
  }
};

// Clear cache (useful for testing or memory management)
const clearCache = () => {
  templateCache.clear();
  translationCache.clear();
};

// Get available templates with serverless-optimized file reading
const getAvailableTemplates = async () => {
  try {
    const templatesDir = path.join(__dirname, '../templates');
    const files = await fs.readdir(templatesDir);
    const templates = files
      .filter(file => file.endsWith('.html'))
      .map(file => {
        const templateNumber = parseInt(file.match(/\d+/)?.[0]);
        return {
          id: templateNumber,
          name: `Template ${templateNumber}`,
          filename: file,
          description: `Professional invoice template ${templateNumber}`
        };
      })
      .sort((a, b) => a.id - b.id);

    return templates;
  } catch (error) {
    console.error('Error getting available templates:', error);
    throw new Error('Failed to get available templates');
  }
};

// Get available locales with serverless-optimized file reading
const getAvailableLocales = async () => {
  try {
    const localesDir = path.join(__dirname, '../locales');
    const files = await fs.readdir(localesDir);
    const locales = files
      .filter(file => file.endsWith('.json'))
      .map(file => {
        const code = file.replace('.json', '');
        const names = {
          'en': 'English',
          'es': 'Español',
          'fr': 'Français',
          'de': 'Deutsch',
          'nl': 'Nederlands',
          'it': 'Italiano',
          'pt': 'Português',
          'sv': 'Svenska',
          'no': 'Norsk',
          'da': 'Dansk'
        };
        return {
          code,
          name: names[code] || code.toUpperCase(),
          filename: file
        };
      });

    return locales;
  } catch (error) {
    console.error('Error getting available locales:', error);
    throw new Error('Failed to get available locales');
  }
};

module.exports = {
  renderTemplate,
  loadTranslations,
  loadTemplate,
  getAvailableTemplates,
  getAvailableLocales,
  clearCache,
  validateInvoiceData,
  calculateTotals
};