const fs = require('fs').promises;
const path = require('path');
const Handlebars = require('handlebars');

// Cache for compiled templates and translations
const templateCache = new Map();
const translationCache = new Map();

// Load and cache translation file with better error handling
const loadTranslations = async (locale) => {
  if (translationCache.has(locale)) {
    return translationCache.get(locale);
  }

  try {
    const translationPath = path.join(__dirname, '../locales', `${locale}.json`);
    
    // Check if file exists first
    try {
      await fs.access(translationPath);
    } catch (accessError) {
      console.warn(`Translation file not found for locale: ${locale}, falling back to English`);
      if (locale !== 'en') {
        return await loadTranslations('en');
      }
      throw new Error('English translation file not found');
    }

    const translationData = await fs.readFile(translationPath, 'utf8');
    const translations = JSON.parse(translationData);
    
    // Validate translation object
    if (!translations || typeof translations !== 'object') {
      throw new Error(`Invalid translation format for locale: ${locale}`);
    }
    
    translationCache.set(locale, translations);
    return translations;
  } catch (error) {
    // If English also fails, return comprehensive default translations
    if (locale === 'en' || error.message.includes('English translation')) {
      const defaultTranslations = {
        invoice: 'Invoice',
        invoiceNumber: 'Invoice Number',
        date: 'Date',
        dueDate: 'Due Date',
        billTo: 'Bill To',
        billFrom: 'Bill From',
        description: 'Description',
        quantity: 'Qty',
        unitPrice: 'Unit Price',
        price: 'Price',
        amount: 'Amount',
        subtotal: 'Subtotal',
        tax: 'Tax',
        shipping: 'Shipping',
        serviceFee: 'Service Fee',
        total: 'Total',
        notes: 'Notes',
        paymentTerms: 'Payment Terms',
        bankAccount: 'Bank Account',
        phone: 'Phone',
        email: 'Email',
        taxNumber: 'Tax Number',
        vatNumber: 'VAT Number',
        thankYou: 'Thank you for your business!',
        generatedOn: 'Generated on',
        poweredBy: 'Generated by Invoice API'
      };
      
      translationCache.set('en', defaultTranslations);
      return defaultTranslations;
    }
    
    // Fallback to English for other locales
    if (locale !== 'en') {
      return await loadTranslations('en');
    }
    
    throw error;
  }
};

// Load and cache template with better error handling
const loadTemplate = async (templateNumber) => {
  const cacheKey = `template_${templateNumber}`;
  
  if (templateCache.has(cacheKey)) {
    return templateCache.get(cacheKey);
  }

  try {
    const templatePath = path.join(__dirname, '../templates', `template${templateNumber}.html`);
    
    // Check if template file exists
    try {
      await fs.access(templatePath);
    } catch (accessError) {
      console.warn(`Template ${templateNumber} not found, falling back to template 1`);
      if (templateNumber !== 1) {
        return await loadTemplate(1);
      }
      throw new Error('Default template not found');
    }

    const templateContent = await fs.readFile(templatePath, 'utf8');
    
    // Validate template content
    if (!templateContent || templateContent.trim().length === 0) {
      throw new Error(`Template ${templateNumber} is empty`);
    }

    const compiledTemplate = Handlebars.compile(templateContent);
    
    templateCache.set(cacheKey, compiledTemplate);
    return compiledTemplate;
  } catch (error) {
    if (templateNumber !== 1) {
      console.warn(`Error loading template ${templateNumber}:`, error.message);
      return await loadTemplate(1);
    }
    
    throw new Error(`Failed to load default template: ${error.message}`);
  }
};

// Register comprehensive Handlebars helpers
const registerHelpers = () => {
  // Format currency helper with better error handling
  Handlebars.registerHelper('formatCurrency', function(amount, currency) {
    try {
      const num = parseFloat(amount) || 0;
      const currencySymbols = {
        'USD': '$',
        'EUR': '€',
        'GBP': '£',
        'CAD': 'C$',
        'AUD': 'A$',
        'JPY': '¥',
        'CHF': 'CHF',
        'SEK': 'kr',
        'NOK': 'kr',
        'DKK': 'kr',
        'INR': '₹',
        'CNY': '¥',
        'BRL': 'R$',
        'ZAR': 'R'
      };
      
      const symbol = currencySymbols[currency] || (currency || '$');
      
      // Handle different currency formatting
      if (currency === 'JPY') {
        return `${symbol}${Math.round(num)}`;
      }
      
      return `${symbol}${num.toFixed(2)}`;
    } catch (error) {
      console.warn('Currency formatting error:', error);
      return amount || '0.00';
    }
  });

  // Format date helper with better error handling
  Handlebars.registerHelper('formatDate', function(dateString, locale) {
    if (!dateString) return '';
    
    try {
      const date = new Date(dateString);
      
      // Check if date is valid
      if (isNaN(date.getTime())) {
        console.warn('Invalid date:', dateString);
        return dateString;
      }
      
      const options = { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      };
      
      return date.toLocaleDateString(locale || 'en-US', options);
    } catch (error) {
      console.warn('Date formatting error:', error);
      return dateString || '';
    }
  });

  // Calculate line total helper
  Handlebars.registerHelper('calculateTotal', function(quantity, price) {
    try {
      const qty = parseFloat(quantity) || 0;
      const prc = parseFloat(price) || 0;
      return (qty * prc).toFixed(2);
    } catch (error) {
      console.warn('Calculate total error:', error);
      return '0.00';
    }
  });

  // Conditional helper
  Handlebars.registerHelper('ifEquals', function(arg1, arg2, options) {
    return (arg1 == arg2) ? options.fn(this) : options.inverse(this);
  });

  // Greater than helper
  Handlebars.registerHelper('ifGreater', function(arg1, arg2, options) {
    return (parseFloat(arg1) > parseFloat(arg2)) ? options.fn(this) : options.inverse(this);
  });

  // String helpers
  Handlebars.registerHelper('uppercase', function(str) {
    return str ? str.toString().toUpperCase() : '';
  });

  Handlebars.registerHelper('lowercase', function(str) {
    return str ? str.toString().toLowerCase() : '';
  });

  Handlebars.registerHelper('capitalize', function(str) {
    if (!str) return '';
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  });

  // Default value helper
  Handlebars.registerHelper('default', function(value, defaultValue) {
    return (value !== null && value !== undefined && value !== '') ? value : defaultValue;
  });

  // Math helpers
  Handlebars.registerHelper('add', function(a, b) {
    return (parseFloat(a) || 0) + (parseFloat(b) || 0);
  });

  Handlebars.registerHelper('subtract', function(a, b) {
    return (parseFloat(a) || 0) - (parseFloat(b) || 0);
  });

  Handlebars.registerHelper('multiply', function(a, b) {
    return (parseFloat(a) || 0) * (parseFloat(b) || 0);
  });

  Handlebars.registerHelper('divide', function(a, b) {
    const divisor = parseFloat(b);
    if (divisor === 0) return 0;
    return (parseFloat(a) || 0) / divisor;
  });

  // URL validation helper
  Handlebars.registerHelper('isValidUrl', function(url) {
    try {
      new URL(url);
      return true;
    } catch {
      return false;
    }
  });

  // JSON helper for debugging
  Handlebars.registerHelper('json', function(context) {
    return JSON.stringify(context, null, 2);
  });

  // Safe string helper
  Handlebars.registerHelper('safe', function(str) {
    return new Handlebars.SafeString(str || '');
  });

  // Number formatting helper
  Handlebars.registerHelper('formatNumber', function(num, decimals = 2) {
    try {
      const number = parseFloat(num) || 0;
      return number.toFixed(decimals);
    } catch (error) {
      console.warn('Number formatting error:', error);
      return num || '0';
    }
  });
};

// Initialize helpers
registerHelpers();

// Validate invoice data
const validateInvoiceData = (invoiceData) => {
  const errors = [];

  // Required fields
  if (!invoiceData.invoiceNumber) {
    errors.push('Invoice number is required');
  }

  if (!invoiceData.date) {
    errors.push('Invoice date is required');
  }

  if (!invoiceData.productOrService || !Array.isArray(invoiceData.productOrService) || invoiceData.productOrService.length === 0) {
    errors.push('At least one product or service item is required');
  }

  // Validate items
  if (invoiceData.productOrService) {
    invoiceData.productOrService.forEach((item, index) => {
      if (!item.name) {
        errors.push(`Item ${index + 1}: Name is required`);
      }
      if (!item.quantity || parseFloat(item.quantity) <= 0) {
        errors.push(`Item ${index + 1}: Valid quantity is required`);
      }
      if (!item.price || parseFloat(item.price) < 0) {
        errors.push(`Item ${index + 1}: Valid price is required`);
      }
    });
  }

  return errors;
};

// Calculate totals safely
const calculateTotals = (invoiceData) => {
  try {
    let subtotal = 0;

    // Calculate subtotal from items
    if (invoiceData.productOrService && Array.isArray(invoiceData.productOrService)) {
      subtotal = invoiceData.productOrService.reduce((sum, item) => {
        const quantity = parseFloat(item.quantity) || 0;
        const price = parseFloat(item.price) || 0;
        return sum + (quantity * price);
      }, 0);
    }

    // Calculate tax
    const taxPercent = parseFloat(invoiceData.taxPercent) || 0;
    const taxAmount = subtotal * (taxPercent / 100);

    // Add other amounts
    const shippingAmount = parseFloat(invoiceData.shippingAmount) || 0;
    const serviceFee = parseFloat(invoiceData.serviceFee) || 0;

    // Calculate total
    const total = subtotal + taxAmount + shippingAmount + serviceFee;

    return {
      subtotal: subtotal.toFixed(2),
      taxAmount: taxAmount.toFixed(2),
      total: total.toFixed(2)
    };
  } catch (error) {
    console.error('Error calculating totals:', error);
    return {
      subtotal: '0.00',
      taxAmount: '0.00',
      total: '0.00'
    };
  }
};

// Main template rendering function with comprehensive error handling
const renderTemplate = async (invoiceData) => {
  try {
    // Validate input data
    const validationErrors = validateInvoiceData(invoiceData);
    if (validationErrors.length > 0) {
      throw new Error(`Validation errors: ${validationErrors.join(', ')}`);
    }

    const templateNumber = invoiceData.template || 1;
    const locale = invoiceData.locale || 'en';

    // Load template and translations
    const [compiledTemplate, translations] = await Promise.all([
      loadTemplate(templateNumber),
      loadTranslations(locale)
    ]);

    // Calculate totals
    const calculatedTotals = calculateTotals(invoiceData);

    // Prepare data for template
    const templateData = {
      ...invoiceData,
      ...calculatedTotals,
      translations,
      locale,
      generatedAt: new Date().toISOString(),
      currentYear: new Date().getFullYear(),
      
      // Add computed boolean values for template conditionals
      hasLogo: !!(invoiceData.companyLogo && invoiceData.companyLogo.length > 0),
      hasBuyer: !!(invoiceData.buyerCompany && Object.keys(invoiceData.buyerCompany).length > 0),
      hasSeller: !!(invoiceData.sellerCompany && Object.keys(invoiceData.sellerCompany).length > 0),
      hasShipping: !!(invoiceData.shippingAmount && parseFloat(invoiceData.shippingAmount) > 0),
      hasServiceFee: !!(invoiceData.serviceFee && parseFloat(invoiceData.serviceFee) > 0),
      hasDueDate: !!(invoiceData.dueDate && invoiceData.dueDate.length > 0),
      hasNotes: !!(invoiceData.notes && invoiceData.notes.length > 0),
      hasPaymentTerms: !!(invoiceData.paymentTerms && invoiceData.paymentTerms.length > 0),
      
      // Format items with calculated totals and safe defaults
      items: invoiceData.productOrService.map((item, index) => ({
        ...item,
        index: index + 1,
        quantity: parseFloat(item.quantity) || 0,
        price: parseFloat(item.price) || 0,
        lineTotal: ((parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0)).toFixed(2),
        name: item.name || `Item ${index + 1}`,
        description: item.description || ''
      })),

      // Ensure currency is set
      currency: invoiceData.currency || 'USD',
      
      // Ensure tax percent is set
      taxPercent: parseFloat(invoiceData.taxPercent) || 0
    };

    // Render template with data
    const html = compiledTemplate(templateData);
    
    if (!html || html.trim().length === 0) {
      throw new Error('Template rendered empty HTML');
    }
    
    return html;

  } catch (error) {
    console.error('Template rendering error:', error);
    throw new Error(`Failed to render template: ${error.message}`);
  }
};

// Clear template and translation caches
const clearCache = () => {
  templateCache.clear();
  translationCache.clear();
  console.log('Template and translation caches cleared');
};

// Get available templates
const getAvailableTemplates = async () => {
  try {
    const templatesDir = path.join(__dirname, '../templates');
    
    // Check if templates directory exists
    try {
      await fs.access(templatesDir);
    } catch (error) {
      console.warn('Templates directory not found');
      return [1];
    }

    const files = await fs.readdir(templatesDir);
    
    const templates = files
      .filter(file => file.endsWith('.html') && file.startsWith('template'))
      .map(file => {
        const match = file.match(/template(\d+)\.html/);
        return match ? parseInt(match[1]) : null;
      })
      .filter(num => num !== null)
      .sort((a, b) => a - b);

    return templates.length > 0 ? templates : [1];
  } catch (error) {
    console.error('Error reading templates directory:', error);
    return [1];
  }
};

// Get available locales
const getAvailableLocales = async () => {
  try {
    const localesDir = path.join(__dirname, '../locales');
    
    // Check if locales directory exists
    try {
      await fs.access(localesDir);
    } catch (error) {
      console.warn('Locales directory not found');
      return ['en'];
    }

    const files = await fs.readdir(localesDir);
    
    const locales = files
      .filter(file => file.endsWith('.json'))
      .map(file => file.replace('.json', ''))
      .sort();

    return locales.length > 0 ? locales : ['en'];
  } catch (error) {
    console.error('Error reading locales directory:', error);
    return ['en'];
  }
};

module.exports = {
  renderTemplate,
  clearCache,
  getAvailableTemplates,
  getAvailableLocales,
  loadTranslations,
  loadTemplate,
  validateInvoiceData,
  calculateTotals
};