const { generatePDF } = require('../services/pdfGenerator');

module.exports = async (req, res) => {
  try {
    console.log('Test endpoint called');
    
    // Set CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
      return res.status(200).end();
    }
    
    // Environment info
    const envInfo = {
      RENDER: process.env.RENDER,
      NODE_ENV: process.env.NODE_ENV,
      isRender: process.env.RENDER === 'true',
      timestamp: new Date().toISOString()
    };
    
    console.log('Environment info:', envInfo);
    
    // Test PDF generation with simple HTML
    const testHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Test Invoice</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          .header { text-align: center; margin-bottom: 30px; }
          .content { margin: 20px 0; }
          .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Test Invoice</h1>
          <p>Environment: ${envInfo.isRender ? 'Render Server' : 'Local Development'}</p>
        </div>
        
        <div class="content">
          <h2>Test Content</h2>
          <p>This is a test invoice generated on ${envInfo.timestamp}</p>
          <p>If you can see this PDF with proper styling, the HTML template rendering is working correctly!</p>
          <p>This PDF was generated using Puppeteer on a traditional Node.js server.</p>
        </div>
        
        <div class="footer">
          <p>Generated by Invoice Generator API on Render</p>
        </div>
      </body>
      </html>
    `;
    
    console.log('Generating test PDF with Puppeteer...');
    const pdfBuffer = await generatePDF(testHtml, { format: 'A4' });
    console.log('Test PDF generated successfully, size:', pdfBuffer.length, 'bytes');
    
    // Return success response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename="test.pdf"');
    res.setHeader('Content-Length', pdfBuffer.length);
    res.status(200).send(pdfBuffer);
    
  } catch (error) {
    console.error('Test endpoint error:', error);
    
    res.status(500).json({
      error: 'Test failed',
      message: error.message,
      environment: {
        RENDER: process.env.RENDER,
        NODE_ENV: process.env.NODE_ENV,
        isRender: process.env.RENDER === 'true'
      },
      timestamp: new Date().toISOString(),
      method: 'Puppeteer on Render Server'
    });
  }
}; 